spring.main.web-application-type=none
spring.ai.openai.base-url=https://bedrock-mantle.us-east-1.api.aws/v1
spring.ai.openai.api-key=${AWS_BEARER_TOKEN_BEDROCK}
spring.ai.openai.chat.model=openai.gpt-oss-120b
