spring.main.web-application-type=none
spring.ai.openai.base-url=https://bedrock-mantle.us-east-1.api.aws/v1
spring.ai.openai.api-key=${AWS_BEARER_TOKEN_BEDROCK}
spring.ai.openai.chat.model=openai.gpt-oss-120b

spring.ai.mcp.client.streamable-http.connections.javadocs.url=https://www.javadocs.dev/mcp
#spring.ai.mcp.client.streamable-http.connections.javadocs.url=http://localhost:8080/mcp

spring.threads.virtual.enabled=true
